const metaData = require('./polkadot_utils/configs/metadata');
const { isConnected } = require('./polkadot_utils/interact');
const {
  getWalletAccounts,
  getWalletAccess,
  getInjector,
} = require('./polkadot_utils/getWalletAccess');
const {
  setUserSubscryptPass,
  setProviderSubscryptPass, refund,
  withdraw,
  subscribe,
  changeDisable,
  editPlan,
  addPlan,
  providerRegister,
  subsCryptPassHashForEachProvider,
  renew,
  addCharacteristicForPlan,
} = require('./polkadot_utils/subscryptSetFunctions');
const {
  getUserPlanCharacteristics,
  getAddressByUsername,
  getSha2,
  getPlanLength,
  retrieveWholeDataWithWallet,
  getUsername,
  providerCheckAuth,
  checkAuthWithUsername,
  providerCheckAuthWithUsername,
  isUsernameAvailable,
  checkAuth,
  getPlanData,
  userCheckAuthWithUsername,
  checkSubscriptionWithUsername,
  checkSubscription,
  retrieveWholeDataWithUsername,
  retrieveDataWithUsername,
  retrieveDataWithWallet,
  userCheckAuth,
  getPlanCharacteristics,
} = require('./polkadot_utils/subscryptDataGetter');
const contract = require('./polkadot_utils/api').getContract();
const testMetaData = require('./polkadot_utils/configs/testConfig');
const config = require('./polkadot_utils/configs/config');
const {
  getBalance, getEvents, abiInstance, transferToken,
} = require('./polkadot_utils/api');

module.exports = {
  abi: metaData,
  contract,
  isConnected,
  getPlanData,
  checkSubscription,
  checkSubscriptionWithUsername,
  retrieveWholeDataWithUsername,
  setUserSubscryptPass,
  setProviderSubscryptPass,
  retrieveDataWithUsername,
  retrieveDataWithWallet,
  userCheckAuth,
  checkAuthWithUsername,
  checkAuth,
  userCheckAuthWithUsername,
  providerCheckAuthWithUsername,
  providerCheckAuth,
  refund,
  withdraw,
  subscribe,
  changeDisable,
  editPlan,
  addPlan,
  providerRegister,
  getWalletAccounts,
  getWalletAccess,
  getInjector,
  subsCryptPassHashForEachProvider,
  renew,
  getSha2,
  retrieveWholeDataWithWallet,
  testMetaData,
  config,
  getUsername,
  isUsernameAvailable,
  getPlanCharacteristics,
  getBalance,
  getEvents,
  abiInstance,
  addCharacteristicForPlan,
  getPlanLength,
  getAddressByUsername,
  getUserPlanCharacteristics,
  transferToken,
};
